### ISSUE TITLE
bugfix release to CPAN?

### ISSUE THREAD

**Issue by justingit** [abw/Badger#11]
Howdy-do, 

Is there a chance that a bugfix release could hit CPAN? A lot of installs of Badger are failing tests, ie: 
 
     t/app/app.t ................ Constants from lexical variables potentially modified elsewhere are deprecated at lib/Badger/Debug.pm line 109.

Which has a fix pushed and committed into this repo https://github.com/abw/Badger/commit/846ff0126912d7be5b756c61ad54574e1705b31e

Badger is used in HTML::Query, which is used in CSS::Inliner which is awesome, but there's no Perl alternative to try, when things fail. 

Appreciate if you could look into this. 

I'm willing to do it myself, if you can authorize me as a maintainer (CPAN ID is: JJSIMONI)

**Comment by akiym** [comment]
@abw Ping ping. Could you release to CPAN? (This also resolves #15)

**Comment by abw** [comment]
Oops, sorry!  It's been lurking on my TODO list for way too long. Thanks for the reminder.

I've just uploaded 0.13 to PAUSE.
